### PR TITLE
fix

### PR DESCRIPTION
**Pull request by serderovsh**
Last time forgot put a tick.
Noticed another mistake.

added
```javascript
options = {
            privateKey: this.tronWeb.defaultPrivateKey,
            address: this.tronWeb.defaultAddress.hex,
            ...options
        };
```
**updateAccount**
Here also added "```options={}```"
```javascript
//old
account_name: stringUtf8toHex(accountName)
//new 
account_name: this.tronWeb.fromUtf8(accountName)
```

### CODE REVIEW

**Comment by serderovsh** [comment]
@Kondax, all change added here.

- **getEventByTransactionID** - fix
- **compile** - not used
- **witness.js** - not used
- **setDefaultBlock()** - simplified condition
- **updateAccount()** - added "options", and changed "account_name"
and freezeBalance, unfreezeBalance - all comments are observed

**Comment by serderovsh** [comment]
[issue](https://github.com/tronprotocol/tron-web/issues/76) - About this bug, there is one solution. But I doubt it is right.

```javascript

export function decodeBase58Address(base58Sting) {
    if (typeof (base58Sting) != 'string')
        return false;

    if (base58Sting.length <= 4)
        return false;

    let address = decode58(base58Sting);

    if (base58Sting.length <= 4)
        return false;

    const len = address.length;
    const offset = len - 4;
    const checkSum = address.slice(offset);

    address = address.slice(0, offset);

    const hash0 = SHA256(address);
    const hash1 = SHA256(hash0);
    const checkSum1 = hash1.slice(0, 4);

    if (checkSum[0] == checkSum1[0] && checkSum[1] == checkSum1[1] && checkSum[2] ==
        checkSum1[2] && checkSum[3] == checkSum1[3]
    ) {
        return address;
    }

    throw new Error('Invalid checksum');
}
```

**Comment by Kondax** [comment]
I would recommend checking if options is a string. If it is, change it to an object with a private key. This will prevent breaking previous compatibility. Other than that looks good!

**Comment by serderovsh** [comment]
> an that looks good!

What method are we talking about?

**Comment by serderovsh** [comment]
> I would recommend checking if options is a string. If it is, change it to an object with a private key. This will prevent breaking previous compatibility.

What method are we talking about?

**Comment by serderovsh** [comment]
> [issue](https://github.com/tronprotocol/tron-web/issues/76) - About this bug, there is one solution. But I doubt it is right.
> 
> ```js
> export function decodeBase58Address(base58Sting) {
>     if (typeof (base58Sting) != 'string')
>         return false;
> 
>     if (base58Sting.length <= 4)
>         return false;
> 
>     let address = decode58(base58Sting);
> 
>     if (base58Sting.length <= 4)
>         return false;
> 
>     const len = address.length;
>     const offset = len - 4;
>     const checkSum = address.slice(offset);
> 
>     address = address.slice(0, offset);
> 
>     const hash0 = SHA256(address);
>     const hash1 = SHA256(hash0);
>     const checkSum1 = hash1.slice(0, 4);
> 
>     if (checkSum[0] == checkSum1[0] && checkSum[1] == checkSum1[1] && checkSum[2] ==
>         checkSum1[2] && checkSum[3] == checkSum1[3]
>     ) {
>         return address;
>     }
> 
>     // return hexStr2byteArray('000000000000000000000000000000000000000000');
>     throw new Error('Invalid checksum'); //added exception
> }
> ```

@Kondax, What do you think about this?

**Comment by Kondax** [comment]
> What method are we talking about?
Any method that takes an `options` parameter. You could add something like this:

```js
if(typeof options == 'string')
    options = { privateKey: options };
```

This way any apps that are currently using a privateKey will work with the new object change, and it will also support TronLink.

RE: The invalid checksum error, I would just change it to `Invalid address provided` - looks good though.

**Comment by Kondax** [comment]
Thanks!

**Pull request merged**
