### PR TITLE
Release 2.0.3

### PR DESCRIPTION
**Pull request by Kondax**
Going to leave this open for a while until we have ironed out any uncaught, miniscule issues.

### CODE REVIEW

**Comment by sullof** [comment]
@Kondax @kookiekrak 
FYI, I am starting a branch to add test coverage.
Since it will take a few days to add the coverage and in the meantime some bug can be fixed, I will pull the request against this branch.

**Comment by sullof** [comment]
Oh, @kookiekrak proposed me to add test coverage, but I see that @Kondax have just started a unit test. Uhm, I wonder which is the best way to interact. Ideas?

**Comment by Kondax** [comment]
@sullof If you want to build off this branch it would be great if you could expand on the tests for the root `TronWeb` class I have in the `test/TronWeb Instance.js` file. I'm going to be separating the test files by module.

Don't worry about functions that depend on prior criteria being setup (such as getEventResult), as I'll move these tests to a seperate file which will create a contract beforehand so that network wipes won't interfere.

Cheers

**Comment by sullof** [comment]
Cool. I will continue the test. In the meantime, I have opened a PR against your master branch
https://github.com/Kondax/tron-web/pull/1

**Comment by kookiekrak** [comment]
Merging this, we're going to build 2.0.3 now

**Pull request merged**
