### PR TITLE
Adding generic subdomains for node specific methods

### PR DESCRIPTION
**Pull request by sullof**
This introduces trx subdomains for specific methods.
Right now it is applied only to getTransaction but in the future, the same approach can be used for any method that can be called against either full node or solidity node.
So, calling
```
tronWeb.trx.getTransaction(txId).then(...)
```
will return the first available transaction. It checks before the full node and if nothing is returned the solidity node.
But, if we call
```
tronWeb.trx.fullNode().getTransaction(txId).then(...)
```
it will check only the full node. And the same for
```
tronWeb.trx.solidityNode.getTransaction(txId).then(...)
```

### CODE REVIEW

**Comment by serderovsh** [comment]
Great idea, I implement it in "tron-api-python"

**Comment by Kondax** [comment]
Do you think it would be a better idea to return a Proxy in the `trx` class? This way we could add this support to all functions of the class with minimal changes to each function, unlike this approach that requires rewriting the request aspect of a lot of functions.

Using this method would also prevent us having to recreate instances of TronWeb. The method you've used will break compatibility with TronLink.

**Comment by sullof** [comment]
@Kondax
@kookiekrak and I discussed many possibilities and we end up with this approach. Since there are very few methods that can be used on both nodes, I would have preferred just having a new method like `getConfirmedTransaction`.
What do you mean exactly when you talk about a proxy?

About promises, I totally agree that we should get rid of callbacks.

**Comment by sullof** [comment]
Consider also that, for now, `.../gettransactionbyid` is the only http api which is callable on both full and solidity nodes.

**Comment by kookiekrak** [comment]
well you also have like getAccount. they're just not documented :\

**Comment by sullof** [comment]
I didn't know about that :-)

**Comment by sullof** [comment]
Instead of calling directly `tronWeb.fullNode` or `tronWeb.solidityNode` we could call a generic `tronWeb.apiRequest` which redirects to one node or the other based on the pathname and a list of api supported by both nodes.
For example, calling
```
this.tronWeb.apiRequest('walletsolidity/gettransactioninfobyid')
```
would be equivalent to
```
this.tronWeb.solidityNode.request('walletsolidity/gettransactioninfobyid')
```
because we are specifying `walletsolidity`.
Now, let's say that we have an object like
```
commonApi = {
    gettransactionbyid: {
        fullNode: 'wallet/gettransactionbyid',
        solidityNode: 'walletsolidity/gettransactionbyid',
        default: 'fullNode'
}
```
Now, in `getTransaction` we could have
```
this.tronWeb.apiRequest('gettransactioninfobyid')
```
and this would call the default, i.e. fullNode. Or
```
this.tronWeb.apiRequest('gettransactioninfobyid', 'solidityNode')
```
to use the solidity node.
The advantage of this approach is that we can just substitute 
```
tronWeb.fullNode.request(
```
with
```
tronWeb.apiRequest(
```
but, even leaving how it is, anything would continue to work fine.
And in the end, we can consider a generic option that activate this or that case.
In the case of `getTransaction` we would have
```
getTransaction(transactionID, preferredNode = false, callback = false) {
        if (utils.isFunction(preferredNode)) {
            callback = preferredNode;
            preferredNode = false;
        }

        if(!callback)
            return this.injectPromise(this.getTransaction, transactionID);

        this.tronWeb.apiRequest('gettransactionbyid', preferredNode, { 
            value: transactionID 
        }, 'post').then(transaction => {
            if(!Object.keys(transaction).length)
                return callback('Transaction not found');
                
            callback(null, transaction);
        }).catch(err => callback(err));
    }
```

In the specific case above, since sometimes the transaction can come before from soliditynode, I was considering to check both and take the first who arrive. In this case, we can put that logic straight into the apiRequest method.

What do you think?

**Comment by Kondax** [comment]
Hmm, so the issue I see with the current solution is that it's _really_ messy. If we want to allow developers to target a specific node type, we need to answer a few questions:
- Is it important that this is controlled as a per-function basis, or set a default for all function types?
- Do we want to modify the API to create "sub domains", or do we want to add a `preferredNode` parameter to all the functions?

My suggestion [regarding using a Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) would have involved allowing developers to call `tronWeb.trx.someMethod()`, `tronWeb.trx.fullNode.someMethod()` or `tronWeb.trx.solidityNode.someMethod()`. As you can see, this is a really odd way of doing it. If I was reading code (without having prior knowledge of TronWeb) and saw `tronWeb.trx.fullNode.someMethod()` I would be under the assumption that `fullNode` was required. This will create a mess when people implementing TronWeb in their projects.

Also, how often will this functionality be used? Correct me if I'm wrong but this seems to be built for a very specific use case. I can't really imagine when it would be beneficial to choose one node type over the other, except for very specific cases. If this is the case, shouldn't we either create two functions (someFunctionFullNode, someFunctionSolidityNode) or instead take a final parameter as `fullNode` or `solidityNode`? I think taking a final parameter `await tronWeb.trx.getTransaction(txID, 'fullNode')` is probably the best solution.

Regarding the `apiRequest` idea: is there really any benefit to doing this other than a simply fetching the node object via the parameter (and method name)? There's only 2 functions (I believe, correct me if wrong) that can use both the full node and solidity node - creating an entirely new request function seems redundant for this. In this case, I suggest:

```js
getMethodName(preferredNode, methodName) {
    if(![ 'fullNode', 'solidityNode' ].includes(preferredNode))
        throw new Error('Invalid preferred node type requested');

    switch(methodName) {
        case 'gettransactionbyid':
            return (preferredNode == 'fullNode' && 'someOtherMethod') || methodName;
    }
}
getTransaction(txID, preferredNode) {
    const methodName = getMethodName(preferredNode, 'gettransactionbyid');
    return this.tronWeb[preferredNode].request(methodName, txID);
}
```

**Comment by sullof** [comment]
I think we agree that it is better to have a simple solution that does not add any complexity, since there is no real general case for this solution.
My preference goes for a new method `getConfirmedTransaction` which removes any ambiguity and does not break any existent app.

Alternatively, we can just add a parameter to `getTransaction` like:
```
tronWeb.trx.getTransaction(txId, preferredNode, ...
```
with three possible values `full`, `solidity` and `any`, defaulting it to `full`.

**Comment by kookiekrak** [comment]
We’re adding fullnode support so its an unconfirmed/possibly confirmed tx.

**Comment by sullof** [comment]
@kookiekrak, it is the opposite. The current getTransaction uses fullNode. We are going to add an alternate method that uses the solidityNode.

**Comment by sullof** [comment]
https://github.com/tronprotocol/tron-web/blob/master/src/lib/trx.js#L130

**Comment by kookiekrak** [comment]
Oh I was thinking getaccount

**Comment by sullof** [comment]
I don't have a name for that :smiley:

**Comment by sullof** [comment]
Anyway, I am modifying this PR and add `getConfirmedTransaction`...

**Comment by sullof** [comment]
About the callbacks, before removing them, I suggest we do a survey to see if any developer is using them instead of promises.

**Comment by Kondax** [comment]
@sullof Sure, sounds like a good idea

**Comment by serderovsh** [comment]
> Instead of calling directly `tronWeb.fullNode` or `tronWeb.solidityNode` we could call a generic `tronWeb.apiRequest` which redirects to one node or the other based on the pathname and a list of api supported by both nodes.
> For example, calling
> 
> ```
> this.tronWeb.apiRequest('walletsolidity/gettransactioninfobyid')
> ```
> would be equivalent to
> 
> ```
> this.tronWeb.solidityNode.request('walletsolidity/gettransactioninfobyid')
> ```
> because we are specifying `walletsolidity`.
> Now, let's say that we have an object like
> 
> ```
> commonApi = {
>     gettransactionbyid: {
>         fullNode: 'wallet/gettransactionbyid',
>         solidityNode: 'walletsolidity/gettransactionbyid',
>         default: 'fullNode'
> }
> ```
> Now, in `getTransaction` we could have
> 
> ```
> this.tronWeb.apiRequest('gettransactioninfobyid')
> ```
> and this would call the default, i.e. fullNode. Or
> 
> ```
> this.tronWeb.apiRequest('gettransactioninfobyid', 'solidityNode')
> ```
> to use the solidity node.
> The advantage of this approach is that we can just substitute
> 
> ```
> tronWeb.fullNode.request(
> ```
> with
> 
> ```
> tronWeb.apiRequest(
> ```
> but, even leaving how it is, anything would continue to work fine.
> And in the end, we can consider a generic option that activate this or that case.
> In the case of `getTransaction` we would have
> 
> ```
> getTransaction(transactionID, preferredNode = false, callback = false) {
>         if (utils.isFunction(preferredNode)) {
>             callback = preferredNode;
>             preferredNode = false;
>         }
> 
>         if(!callback)
>             return this.injectPromise(this.getTransaction, transactionID);
> 
>         this.tronWeb.apiRequest('gettransactionbyid', preferredNode, { 
>             value: transactionID 
>         }, 'post').then(transaction => {
>             if(!Object.keys(transaction).length)
>                 return callback('Transaction not found');
>                 
>             callback(null, transaction);
>         }).catch(err => callback(err));
>     }
> ```
> In this PR, since sometimes the transaction can come from solidity node before that from the full node I am connected with, I am checking both and take the first that returns a result. In this case, we can put this logic into the apiRequest method, adding maybe another parameter to the `commonApi` object.
> 
> What do you think?

Just an opinion: It is better to make a similar option than to create unnecessary methods to avoid confusion.

getConfirmedTransaction()
getConfirmedAccount()
....

**Pull request merged**
