### PR TITLE
Fixing signed transactions when there are custom data

### PR DESCRIPTION
**Pull request by sullof**
Referring to https://github.com/tronprotocol/tron-web/issues/104
This fixes custom data in signed transactions. 

You can see a test at https://github.com/tronprotocol/tron-web/pull/91/files#diff-3aaae82233adb273aa0e0efa039bd061R57

### CODE REVIEW

**Comment by metjm** [comment]
This is the exact reason why the nodes should not have this awful endpoint. 

This commit is reckless and incredibly dangerous. What the fuck

**Comment by sullof** [comment]
You guys are right. My fault. I didn't think about that. I am closing it and work on the previous way.

**Comment by serderovsh** [comment]
> This is the exact reason why the nodes should not have this awful endpoint.
> 
> This commit is reckless and incredibly dangerous.

What is the danger?

**Comment by serderovsh** [comment]
Alternatively you will not add!
2 options: Online transaction signature and offline signature.
And everyone is happy)

**Comment by serderovsh** [comment]
> @serderovsh Sending the private key to the node is generally a really bad idea.
> 
> This commit actually did that by default, and it kinda makes me reconsider if we should maintain our own fork of tron-web because there is a good chance we would've used this version had @Kondax not randomly seen the pull request.
> 
> It's bad enough that the node is used for constructing the transaction object imo, but sending my private key to the node provider means that for applications like wallets the person that hosts the node could very easily steal all private keys.
> 
> This shouldn't be added as option either, there are too many bad or lazy programmers out there that will use it without realizing how incredibly insecure it is. We've asked tron before to completely remove that endpoint because it just invites bad practices, sadly it's still there.

In some cases, it is convenient.

No need to disassemble the "Proto", and the economy is very time consuming.
Otherwise, it will not work with "raw_data.data".

**Comment by serderovsh** [comment]
@metjm I fully agree with you that it is not safe!
But this method simplifies the work. (If you need to add a note to the transaction)

**Comment by Kondax** [comment]
It's not something we'll be adding. It's dangerous and a bad idea. We cannot trust developers to know the difference. Malicious nodes could very easily steal funds.

I'll limit this conversation for now. We should look into correcting the signing method as opposed to using the node to sign requests.

**Pull request closed without merging**
