### PR TITLE
[READY]: Development of TronWeb@2.0.0

### LINKED ISSUE #8: Proposal for new TronWeb API
# TronWeb API Proposal
`TronWeb` was hastily developed without any prior planning on how to design the specifications. This has lead to an unorganised, slightly ambiguous API that will lead to potential developer confusion. It also means that migrating from `Web3` -> `TronWeb` will be a daunting task.

One of the many benefits of the `TVM` is that developers can ship nearly 1:1 smart contracts on both the `TVM` and `EVM`. Interacting with these contracts shouldn't be different.

`TronWeb` has been created to facilitate the need of interacting with the blockchain and smart contracts from the browser, desktop applications (Electron), mobile applications (*-native) and NodeJS. This proposal is for a new API spec that will resemble `Web3` (whilst still incorporating native TRON features) as much as possible. Whilst I have attempted to include all `Web3` functionality, some of it is unique to Ethereum. I have ported the spec for as many functions as possible.

TRON has two request protocols:
- gRPC
- HTTP

**For the time being we plan on only supporting the HTTP protocol.** _However in the future_ we would like developers to be able to pass `new TronWeb.providers.gRPCProvider()` if they want to run over gRPC instead.

All `TronWeb` methods will return a promise. They will all take a last, optional parameter as a callback using the [error-first-style](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/) callback. If a callback is passed the promise will not be returned.

Each method would essentially do the following (should be interpreted as pseudo code):
```js
const injectPromise = (func, ...args) => {
    return new Promise((resolve, reject) => {
        func(...args, (err, res) => {
            if(err)
                reject(err);
            else resolve(res);
        });
    });
},

const promiseInjector = scope => {
    return (func, ...args) => {
        return injectPromise(func.bind(scope), ...args);
    }
}

class TronWeb {
    injectPromise = utils.promiseInjector(this);

    getEventByTransacionID(transactionID, callback = false) {
        if(!callback)
            return this.injectPromise(this.getEventByTransacionID, transactionID);

        const event = getEventSomehow(transactionID);
        callback(null, event);
    }
}
```

This will maintain `Web3` compatibility whilst still offering the benefits of promises.

## HTTP Provider
This will send RPC over HTTP to nodes that support it. The provider will be accessible under `new TronWeb.providers.HttpProvider()` and take the following arguments:
- `host`: The host of the node, in the format `http://ip:port`
- `[timeout=30000]`: The global timeout for requests to the node in milliseconds. This should be able to be overridden on a per-use scenario.
- `[user=false]`: User for HTTP authentication
- `[password=false]`: Password for HTTP authentication, requires `user` to be set.
- `[headers={}]`: Additional headers to be attached to all requests. Individual requests will override these headers.
- `[statusPage='/']`: Page to query when calling `isConnected()`

The following methods will be exposed:
- `setStatusPage(statusPage = '/')`: Sets the status page to query.
- `async isConnected()`: Returns type `boolean`, this will make a call to the node (fetch latest block number) to verify that the mode connection is successful.
- `async request(url, payload = {}, method = 'get')`: Returns a promise. The promise will be resolved if the node sends a 2xx status, otherwise it will throw the error.

For more details see [`web3.providers.HttpProvider`](https://github.com/ethereum/web3.js/blob/develop/lib/web3/httpprovider.js).

## TronWeb API
`class TronWeb`:
- constructor(fullNode, solidityNode, eventServer = false, privateKey = false):
	- `fullNode`: A provider connected to a valid full node
	- `solidityNode`: A provider connected to a valid solidity node
	- `[eventServer]`: Optional for smart contract events. Expects a valid event server URL
        - `[privateKey]`: Optional default private key used when signing transactions
	
- isConnected():
	- Returns an object with the structure `{ fullNode: bool, solidityNode: bool, eventServer: bool }`

- setFullNode(provider):
	- `provider`: A provider connected to a valid full node

- setSolidityNode(provider):
	- `provider`: A provider connected to a valid solidity node

- setEventServer(eventServer):
	- `[eventServer=false]`: False to unset the event server, or a valid event server URL

- currentProviders():
	- Returns an object with the structure `{ fullNode: TronWeb.provider, solidityNode: TronWeb.provider, eventServer: string|bool }`

- currentProvider():
    -An alias of `currentProviders()`

- sha3(string, options):
	- `string`: The string to hash (using Keccak-256 SHA3 Algorithm)
	- `[options={}]`: Configure `encoding: hex` if the string to hash is encoded in hexadecimal format

- toHex(input):
	- `input`: Either a string, number, object, array or BigNumber. Objects / Arrays will be stringified with `JSON.stringify` first.

- toAscii(hex):
	- `hex`: Hexadecimal-encoded string to be converted to ASCII

- fromAscii(string):
	- `string`: An ASCII string to be converted to hexadecimal

- toDecimal(hex):
	- `hex`: Hexadecimal-encoded string to be converted to its number representation

- fromDecimal(number):
	- `number`: Number (or string) to be converted to hexadecimal

- fromSun(sun):
	- `sun`: Number in SUN (1 / 1,000,000 TRX) to be converted to TRX

- toSun(trx):
	- `trx`: Number in TRX to be converted to SUN (1 / 1,000,000 TRX)

- toBigNumber(amount):
	- `amount`: Amount that's a number, number string or hexadecimal string of a number to be converted to a BigNumber

- isAddress(address):
	- `address`: Either hex encoded or base58 encoded address

- address:
	- fromHex(address):
		- `address`: Hexadecimal encoded address
		- Returns the base58 representation of the supplied address

	- toHex(address):
		- `address`: Base58 encoded address
		- Returns the hexadecimal representation of the supplied address

- trx:
	- defaultAccount
		- The default account (hexadecimal address) to use when creating transactions

	- defaultBlock
		The default block to use when creating transactions. Can be one of the following:
		-	Number: a block number
		-	String "earliest": the genesis block
		-	String "latest": the latest block (at the time of creating the transaction)

	- getBalance(address [, callback]):
		- `[address=this.defaultAccount]`: The address to fetch the balance of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getBandwidth(address [, callback]):
		- `[address=this.defaultAccount]`: The address to fetch the bandwidth of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getBlock(blockIdentifier [, callback]):
		- `[blockIdentifier=this.defaultBlock]`: The block to fetch
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getBlockTransactionCount(blockIdentifier [, callback]):
		- `[blockIdentifier=this.defaultBlock]`: The block to list the transaction count of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTransaction(transactionHash [, callback]):
		- `transactionHash`: The transaction hash of the transaction to fetch
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTransactionFromBlock(blockIdentifier, index [, callback]):
		- `blockIdentifier`: The block to search
		- `index`: The index of the transaction in the fetched block
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTransactionCount(address [, callback]):
		- `address`: Hexadecimal address to fetch the transaction count of
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTokenFromAddress(address [, callback]):
		- `address`: Address of the token issuer
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getTokenFromID(assetID [, callback]):
		- `assetID`: The asset ID (the token name) of the token
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- getContract(contractAddress [, callback]):
		- `contractAddress`: Hexadecimal address of the contract
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- listNodes([callback]):
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the list of connected nodes.	

	- listSuperRepresentatives([callback]):
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns a list of all accounts that have applied for SR.

	- listAssets():
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns a list of all issued tokens.

	- listAssetsPaginated(limit [, offset [, callback]]):
		- `limit`: Total amount of tokens to fetch
		- `offset`: Offset at which to start returning tokens
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- timeUntilNextVoteCycle([callback]):
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- sendTransaction(to, amount, privateKey, [, callback]):
		- `to`: Hexadecimal address of the receiving account
		- `amount`: Amount of TRX **in SUN** to send
		- `privateKey`: Hexadecimal private key of the account to send the TRX from
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the transaction result.

	- sendAsset(to, amount, assetID, privateKey, [, callback]):
		- `to`: Hexadecimal address of the receiving account
		- `amount`: Amount of the asset to send
		- `assetID`: The asset ID (name of the token) to send
		- `privateKey`: Hexadecimal private key of the account to send the asset from
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the transaction result.

	- sendRawTransaction(signedTransaction [, callback]):
		- `signedTransaction`: An already signed transaction to broadcast to the network
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the transaction result.

	- sign(transaction, privateKey [, callback]):
		- `transaction`: An unsigned hexadecimal transaction to sign
		- `privateKey`: Hexadecimal private key of the account to sign the transaction with
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the signed transaction.

	- contract(abiArray):
		- `abiArray`: An array of with descriptions of functions and events of the contract
		- Returns a new contract object which can be initiated as follows:
		```js
		const MyContract = tronWeb.trx.contract(abiArray);
		// Get contract from address
		const contractInstance = MyContract.at(address);
		// Deploy new contract
		const contractInstance = MyContract.new(params);
		const contractData = contractInstance.getData(); // hex representation of the contract
		```

- witness:
	- apply(privateKey, url [, callback]):
		- `privateKey`: Hexadecimal private key of the account applying for SR
		- `url`: Homepage url of the SR
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the result from the node. This costs 9,999 TRX.

	- submitVotes(votes [, callback]):
		-  `votes`: Object in the format `{ [srAddress]: voteCount }` for the SRs to vote for. `voteCount` is in SUN.
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the result from the node.

	- withdraw(privateKey [, callback]):
		- `privateKey`: Hexadecimal private key of the SR requesting the withdraw
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the result from the node.

-	transactionBuilder:
	-	createToken(tokenObject [, callback]):
		-	`tokenObject`: Token object to send to the node with the following structure:
			```js
			{
				name: name of the token,
				abbr: abbreviation of the token,
				url: homepage url of the token,
				description: description of the token,
				totalSupply: Integer value of the total token supply,
				frozenSupply: Amount of the token to be frozen when created (defaults 0),
				frozenDuration: Amount of days to freeze the frozenSupply for (minimum 3),
				startTime: Timestamp of the start of the token sale,
				endTime: Timestamp of the end of the token sale,
				trxAmount: Amount the token costs in SUN
			}
			```
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- sendTrx(to, amount, from [, callback]):
		- `to`: Hexadecimal address of the recipient
		- `amount`: Amount of TRX **in SUN** to send to the recipient
		- `from`: Hexadecimal address of the sender
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- sendAsset(to, amount, assetID, from [, callback]):
		- `to`: Hexadecimal address of the recipient
		- `amount`: Amount of the asset to send
		- `assetID`: The asset ID (the token name) to send to the recipient
		- `from`: Hexadecimal address of the sender
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- purchaseAsset(tokenIssuer, assetID, amount, buyer [, callback]):
		- `tokenIssuer`: Hexadecimal address of the owner of the token
		- `assetID`: The asset ID (the token name) to purchase
		- `amount`: The amount of the token to purchase
		- `buyer`: Hexadecimal address of the buyer
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- freezeBalance(address, amount, duration [, callback]):
		- `address`: Hexadecimal address of the account requesting the freeze
		- `amount`: Amount of TRX **in SUN** to freeze
		- `[duration=3]` Duration (in days) to freeze the TRX for. Minimum of 3.
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned. 
		- Returns the unsigned transaction.

	- unfreezeBalance(address [, callback]):
		- `address`: Hexadecimal address of the account requesting the unfreeze
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

	- vote(votes, address [, callback]):
		-  `votes`: Object in the format `{ [srAddress]: voteCount }` for the SRs to vote for. `voteCount` is in SUN.
		- `address`: Hexadecimal address of the voter.
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.
	
	- applyForSR(address, url [, callback]):
		- `address`: Hexadecimal address of the account applying for SR.
		- `url`: Homepage url of the SR
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction. This will cost 9,999 TRX.

	- withdrawBlockRewards(address [, callback]):
		- `address`: Hexadecimal address of the SR requesting the withdraw
		- `[callback=false]`: Function to call with the result. If omitted a promise is returned.
		- Returns the unsigned transaction.

  - createSmartContract(abi, bytecode, feeLimit, address, callValue, bandwidthLimit [, callback]):
    - `abi`: The contract's ABI
    - `bytecode`: The contract's bytecode in HEX
    - `feeLimit`: Maximum TRX consumption **in SUN**
    - `address`: Hexadecimal address of the account requesting to create the contract
    - `[callValue=0]`: Optional amount of TRX in SUN to pay into the contract
    - `[bandwidthLimit]0]`: Optional percentage of the issuer's bandwidth to share with contract users
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.

	- triggerSmartContract(contractAddress, functionSelector, callValue, feeLimit, parameters, address [, callback]):
    - `contractAddress`: Hexadecimal address of the smart contract
    - `functionSelector`: Signature of the function to trigger
    - `callValue`: The amount of TRX **in SUN** to pay into the contract
    - `feeLimit`: Maximum TRX consumption **in SUN**
    - `[parameters=[]]`: Optional parameters to pass to the function
    - `address`: Hexadecimal address of the account requesting the trigger
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
    - Returns the unsigned transaction.
    
- getEventResult(contractAddress, eventName, blockNumber [, callback]):
    - `contractAddress`: Hexadecimal address of the smart contract
    - `[eventName=false]`: Optional name of the event to query
    - `[blockNumber=false]`: Optional block number to query events from
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
    - Returns any found events.
  
- getEventByTransactionID(transactionID [, callback]):
    - `transactionID`: The transaction ID to query for events
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
  
- createAccount([callback]):
    - `[callback=false]`: Function to call with the result. If omitted a promise is returned.
    - Returns a keypair for a new account.
  
There are some contracts missing from the API spec. This does not mean they will not be included - this proposal
is merely for showing how the API could be structured. The API will still export all contract types.
  
## Example
```js
import TronWeb from 'TronWeb';

const fullNode = new TronWeb.providers.HttpProvider('http://127.0.0.1:8090');
const solidityNode = new TronWeb.providers.HttpProvider('http://127.0.0.1:8091');
const eventServer = 'http://127.0.0.1:18891'; // This will only ever run over HTTP, not gRPC

const tronWeb = new TronWeb(fullNode, solidityNode, eventServer);

tronWeb.createAccount(({ privateKey, address }) => {
  console.log(`New account generated with privateKey ${privateKey}, hexadecimal address ${address}`);
});
```

## Node Proxying
Nodes run over HTTP (not HTTPS) which can pose a security risk. Requests are vulnerable to MiTM
and can therefore risk the funds of the developer. For this reason, TronWatch have created the following proposal:

`https://proxy.tron.watch/nodeIP:nodePort/someNodeMethod`

TronWatch will provide a proxy endpoint that proxies all requests to the specified node. This can prevent _local MiTM_,
such as if a user were using public wifi. The connection between the TronWatch server and the node will not be secured,
therefore it is vulnerable to MiTM during that process and is unfortunately not a solution for all.

The proxy function will be published in a GitHub repository with deployment instructions should a developer wish to deploy
their own proxy.

### PR DESCRIPTION
**Pull request by Kondax**
This pull request will serve as tracking the progress of creating 2.0.0.

Please see the new API proposal at #8.

To contribute, please see [@Kondax/tron-web](https://github.com/Kondax/tron-web/tree/2.0.0).

Closes #8

### CODE REVIEW

**Comment by Kondax** [comment]
#3cdedf3 ports all the required TRON utility files to the new folder structure. They have been (or quickly attempted to) rewritten with ES6.

There's duplicates in them and the code is overall a mess. File sizes can be reduced dramatically.

Rewriting these utility files are outside the scope of 2.0.0, but they should definitely be rewritten at a later date.

**Comment by Kondax** [comment]
Core
- [x] isConnected()
- [x] setFullNode(provider)
- [x] setSolidityNode(provider)
- [x] setEventServer(provider)
- [x] currentProviders()
- [x] currentProvider()
- [ ] sha3(string, options)
- [x] toHex(input)
- [x] toAscii(hex)
- [x] fromAscii(string)
- [x] toDecimal(hex)
- [x] fromDecimal(number)
- [x] fromSun(sun)
- [x] toSun(trx)
- [x] toBigNumber(amount)
- [x] isAddress(address)
- [ ] compile(soliditySource)
- [ ] createSmartContract(abi, bytecode, feeLimit, address, callValue, bandwidthLimit)
- [ ] getEventResult(contractAddress, eventName, blockNumber)
- [ ] getEventByTransactionID(transactionID)
- [x] createAccount()

Address
- [x] fromHex(address)
- [x] toHex(address)

TRX
- [ ] defaultAccount `This should be moved to the root TronWeb class?`
- [ ] defaultBlock `This too, should we also add defaultPrivateKey?`
- [ ] getBalance(address)
- [ ] getBandwidth(address)
- [ ] getBlock(blockIdentifier)
- [ ] getBlockTransactionCount(blockIdentifier)
- [ ] getTransaction(transactionHash)
- [ ] getTransactionFromBlock(blockIdentifier, index)
- [ ] getTransactionCount(address)
- [ ] getTokenFromAddress(address)
- [ ] getTokenFromID(assetID)
- [ ] getContract(contractAddress)
- [ ] listNodes()
- [ ] listSuperRepresentatives()
- [ ] listAssets()
- [ ] listAssetsPaginated(limit, offset)
- [ ] timeUntilNextVoteCycle()
- [ ] sendTransaction(to, amount, privateKey)
- [ ] sendAsset(to, amount, assetID, privateKey)
- [ ] sendRawTransaction(signedTransaction)
- [ ] sign(transaction, privateKey)
- [ ] contract(abiArray)

Witness
- [ ] apply(privateKey)
- [ ] submitVotes(votes)
- [ ] withdraw(privateKey)

Transaction Builder
- [ ] createToken(tokenObject)
- [ ] sendTrx(to, amount, from)
- [ ] sendAsset(to, amount, assetID, from)
- [ ] purchaseAsset(tokenIssuer, assetID, amount, buyer)
- [ ] freezeBalance(address, amount, duration)
- [ ] unfreezeBalance(address)
- [ ] vote(votes, address)
- [ ] applyForSR(address, url)
- [ ] withdrawBlockRewards(address)

**Comment by Kondax** [comment]
Some recent thoughts over new API proposal:
- We should alias `sendTrx()` to `sendTransaction()`
- We should alias `signTransaction()` to `sign()`
- `defaultAccount` should be renamed to `defaultPrivateKey`
- `defaultBlock` and `defaultAccount` should be moved to the root class
- We should add `setDefaultBlock(blockID)` and `setDefaultAccount(privateKey)` to the root class
- We should add a `Token` class, with the methods:
  - `class Token`
    - `createAsset(tokenObject)`
    - `updateAsset(tokenObject)`
    - `purchaseAsset(tokenID)`
- Above brings on another issue: Do we refer to tokens as `token` or `asset`? I much prefer `token` and feel as though `asset` was probably poor translation. I think it'd make more sense to use `token` instead. What about `basicToken` to distinguish them from ERC20 tokens?
  - `class BasicToken`
    - `createToken(tokenObject)`
    - `updateToken(tokenObject)`
    - `purchaseToken(tokenID)`

What are your thoughts @kookiekrak?

**Comment by Kondax** [comment]
It seems as though `Web3` has removed support for compiling smart contracts, therefore the compile method will be removed.

**Comment by Kondax** [comment]
`getContract(contractAddress)` has been implemented by returning an object.

Once the `Contract` class has been implemented this will be cast to a new instance.

**Comment by Kondax** [comment]
Yeah that's fine

**Comment by kookiekrak** [comment]
@Kondax were you able to test publishing contracts on 3.1 using this?

**Comment by Kondax** [comment]
@kookiekrak I have not tested that yet, I've been implementing all the transaction creation methods. I'll add the signing and broadcasting functionality tomorrow which will give me a chance to test publishing contracts then.

**Comment by Kondax** [comment]
All transaction related functionality, including event results are complete.

Remaining is the compile functionality (which _should_ be as simple as exporting solc) and the `Contract` class. 

Once the above is complete an example will be created for using TronWeb in the browser. Server examples are already in place.

**Comment by Kondax** [comment]
Added support for passing parameters when creating (deploying) smart contracts. See https://github.com/tronprotocol/java-tron/pull/1523.

**Comment by Kondax** [comment]
**Contract events have been added**

Using TronGrid, TronWeb is now capable of polling for contract events. You can run the below example:

```js
const newContract = await tronWeb.contract().at('416b8188c438f17950b03b3b25b93a0332293c3166');

const eventListener = newContract.events(event => {
    console.group('New event received');
        console.log('- Contract Address:', event.contract);
        console.log('- Event Name:', event.name);
        console.log('- Transaction:', event.transaction);
        console.log('- Block number:', event.block);            
        console.log('- Result:', event.result, '\n');
    console.groupEnd();
}).start(err => {
    if(err)
        return console.error('Failed to start event listener:', err);

    console.log('Event listener started\n');
});

// This is a pure function so it's only executed on the local node 
newContract.methods.test(1, 1000000).call().then(async output => {
    console.group('Contract "test" result');
        console.log('- Output:', output.toString(), '\n');
    console.groupEnd();

    // The "send" function propagates to all SRs, which can take up to 1 minute
    await newContract.methods.multiply(1, 1000000).send();
    await newContract.methods.multiply(2, 1000000).send();
    await newContract.methods.multiply(3, 1000000).send();

    return newContract.methods.getLast().call();
}).then(output => {
    console.group('Contract "getLast" result');
        console.log('- Output:', output.join(', '), '\n');
    console.groupEnd();

    setTimeout(() => {
        // Give the listener time to receive events before stopping
        eventListener.stop();
    }, 5 * 1000);        
}).catch(err => console.error(err));
```

This should yield the following output (not necessarily in the same order):

```js
Contract "test" result
  - Output: 1000000

Event listener started

Contract "getLast" result
  - Output: 3, 1000000, 3000000

New event received
  - Contract Address: TKmeUnJdZ7diF7dQu8LesqFMdJgJrQLkXB
  - Event Name: Message
  - Transaction: cec2a2fdfb98393da06f3262890b4579c2ba0827a72ebf36f634161842098bc9
  - Block number: 1441
  - Result: [ '2', '1000000', '2000000' ]

New event received
  - Contract Address: TKmeUnJdZ7diF7dQu8LesqFMdJgJrQLkXB
  - Event Name: Message
  - Transaction: ca78a4ea545aee21efd1720880ca0532d1c61e5ce6b0871d1ba61f4b3d83aabc
  - Block number: 1441
  - Result: [ '1', '1000000', '1000000' ]

New event received
  - Contract Address: TKmeUnJdZ7diF7dQu8LesqFMdJgJrQLkXB
  - Event Name: Message
  - Transaction: 82fa3e5dde0007ed216dbb8b67b3407a37c7b7eed90b7cb1f876c78271752aa9
  - Block number: 1442
  - Result: [ '3', '1000000', '3000000' ]
```

The contract method `multiply` emits an event with the two inputs and the result of multiplying the two together. As you can see above three events are emitted - one for each multiply call.

**Comment by Kondax** [comment]
Added **specific** event watching. Example below:

```js
newContract.methods.Message().watch((err, event) => {
        if(err)
            return console.error('Error with "Message" event:', err);

        console.group('New event received');
            console.log('- Contract Address:', event.contract);
            console.log('- Event Name:', event.name);
            console.log('- Transaction:', event.transaction);
            console.log('- Block number:', event.block);            
            console.log('- Result:', event.result, '\n');
        console.groupEnd();
    });
```

**Comment by Kondax** [comment]
Added `getTransactionFromBlock(block, index)`

**Comment by sullof** [comment]
@Kondax You did an impressive job with this 👍 
I propose that we add test coverage in a new PR as soon as this is ready to go.
@kookiekrak, what do you think?

**Comment by Kondax** [comment]
Thanks!

Test coverage and full documentation would be great. I'm working with @kookiekrak at the moment to port milliondollarhomepage to TronWeb, and once that's done and we've verified that everything's working the way it should I can look into adding some proper unit tests.

**Comment by Kondax** [comment]
Previously when calling a contract method that failed the callback would resolve with the transaction ID. Instead the callback is now "rejected" with an object `{ error, transaction }`. The `error` property returns a string whereas the `transaction` property returns the signed transaction.

This should help to distinguish failures by checking for a `transaction` property on the error response.

**Comment by Kondax** [comment]
Added support for contract methods to be accessed directly from the contract object as opposed the `.methods` parameter.

```diff
- await contract.methods.Message().call();
+ await contract.Message().call();
```

The contract will only bind methods that do not overwrite current properties of the contract object, such as `new`, `at`, `events`, `hasOwnProperty`, `toString` etc. These would need to be accessed from the `.methods` parameter.

Like with the `.methods` parameter, the function selector and signature for each method is also bound to the contract object.

**Comment by sullof** [comment]
I am trying to develop contracts using this version of tron-web (since I was unable to make tron-box working). I tried the example. It fails anytime you try to get some specific data. 
For example, the following code fails because it cannot find the transaction. I wonder if trongrid has been restarted and the existent transaction where flushed during the execution.

```
try {
      const transaction = await tronWeb.trx.getTransaction('2429559770c908e262d2510592cc0948f6bdec9288c528ef5ed6a22ea75148de');

      console.group('Transaction');
      console.log('- Hash:', transaction.txID);
      console.log('- Transaction:\n' + JSON.stringify(transaction, null, 2), '\n');
      console.groupEnd();

    } catch(err) {
      console.error('Error in tronWeb.trx.getTransaction', err.message)
    }
```
(BTW, I added the try catch to continue the execution, I can add the same to anything and push a commit, if you like).

I also tried the example connecting it to my private network and it worked the same way, which is useful because it shows that the problem is with tronbox and not with my private network setting, helping me.

**Comment by Kondax** [comment]
@sullof yeah, aware of that sorry. The demo was actually only really meant for internally testing and trongrid is reset daily or so.

I'll change that up so the error is caught correctly instead of just throwing an uncaught promise error. Didn't do that in the first place as I originally added that example not knowing the network would be reset.

**Comment by kookiekrak** [comment]
good to go!

**Pull request merged**
