### PR TITLE
Fixing trx.createProposal

### PR DESCRIPTION
**Pull request by sullof**
Fix trx.createProposal because the parameters expected by the `/wallet/proposalcreate` (see https://github.com/tronprotocol/Documentation/blob/2fa6ec8ef1bf2020b22467e6aef939e2357ecf4b/TRX/Tron-http.md) is not an object, but an array of objects.

Also, adding coverage to TronWeb I found that axios expect that parameters is `null` in a POST. If it is an empty object the request is never executed.

### CODE REVIEW

**Comment by sullof** [comment]
@kondax What do you think of the fix in the HttpProvider. Just try to call
```
tronWeb.trx.listProposals() 
```
to see the problem.

**Comment by Kondax** [comment]
@sullof I'm happy for you to add that, however the underlying issue for that is actually in the java-tron HTTP API and not TronWeb itself. The API is a complete and utter mess, but I know that won't be fixed for a very long time.

**Comment by Kondax** [comment]
Also, is the `/wallet/proposalcreate` method for creating multiple proposals, or is it just the API being stupid and expecting an array for no reason at all?

It might be a better idea to keep `createProposal` as a single object, and just send it as an array to the API.

**Comment by sullof** [comment]
Actually the problem is not with the api itself, but with the proxied api. If you run that against java-tron it works, but if there is a proxy in front of the api in order to allow web pages to use the api (like in Tron Quickstart) it won't work. Since this solution works in both cases, I propose we change it. Of course, if you don't think that there can be some case where it would not work.

**Comment by sullof** [comment]
About `createProposal`, if you call the api with a single object it throws an error.

**Comment by Kondax** [comment]
Ah okay, that's understandable. Changing it is fine.

For the `createProposal` I'd recommend just taking a single object input and sending `[ theObject ]` as the post data for the API in that case

**Comment by sullof** [comment]
Thanks. That makes sense. Also because it keeps compatibility with the current version.

**Pull request merged**
