### PR TITLE
Fix issues 176

### PR DESCRIPTION
**Pull request by sullof**
This should fix https://github.com/tronprotocol/tron-web/issues/176
@kondax Would you verify it, please?

### CODE REVIEW

**Comment by Kondax** [comment]
I think we should also remove the address from `defaultOptions`. Don't forget the change for the send method too

**Comment by sullof** [comment]
If we remove from there, there are other errors around. For now, I will merge this way. Later I will try to figure out how to avoid those errors.

**Comment by zscc** [comment]
Any update on this?

**Comment by Kondax** [comment]
@zscc I do not believe this is fully fixed.

**Comment by sullof** [comment]
I did a partial fix because I was unable to replicate all the cases reported. I just reopened the issue https://github.com/tronprotocol/tron-web/issues/176.
@kondax Out of curiosity, since you seem to understand perfectly the issue, I wonder why you don't do a pull request.

**Comment by Kondax** [comment]
I have not had the time recently, but I will look into it when I get a
chance for you

**Pull request merged**
