### PR TITLE
Update

### PR DESCRIPTION
**Pull request by serderovsh**

### CODE REVIEW

**Comment by serderovsh** [comment]
Don't update yet, I'll add a couple of methods.

**Comment by serderovsh** [comment]
@Kondax, event moved to a separate object

**Comment by serderovsh** [comment]
Removed block
**Documentation for TronWeb 1.0** - links are not working

**Comment by serderovsh** [comment]
@Kondax, In the main project description, add a link https://developers.tron.network/v1.0/reference

Opposite description: _Javascript API Library for interacting with the TRON Network. Similar to web3.js_

**Comment by Kondax** [comment]
I won't be approving this PR as it contains major breaking changes. We don't plan on adding event functions to their own scope anytime soon.

**Comment by serderovsh** [comment]
OK, this was not the final version of the update.

**Pull request closed without merging**
