### PR TITLE
Make signing optional for sendTransaction and sendToken

### PR DESCRIPTION
**Pull request by Kondax**
These functions give the ability to create, sign and broadcast a transaction from one call. The issue with this is that third party applications that hook into the signing service of TronWeb (such as TronLink) might not expose a private key to TronWeb, meaning these functions cannot be used as no private key is set.

This commit changes out the `privateKey` parameter for an `options` object parameter with two keys - `address` and `privateKey`. They are both set to the default values set in TronWeb.

This means that you can call the function and it will create the transaction with the passed (or default) address, however signing will be done by a third party. This means the transaction can then be broadcasted without requiring a private key to be exposed to TronWeb.

This also fixes a typo that prevented `listExchanges()` from working correctly.

### CODE REVIEW

**Comment by sullof** [comment]
@Kondax I know, this has been merged, but this PR breaks any Dapp where someone was passing a private key to sendTransaction. In fact, now, that would cause an error. Instead, we could just add something like

```
        if(utils.isFunction(options)) {
            callback = options;
            options = {};
        } else if(utils.isString(options)) {
            options = { privateKey: options};
        }

```
In the future, we can deprecate that and remove it. WDYT?

**Comment by sullof** [comment]
At least, if `options` is a String we should return a specific error that alerts the developer that the expected parameter is changed.

**Comment by sullof** [comment]
Also, in the code
```
        options = {
            privateKey: this.tronWeb.defaultPrivateKey,
            address: this.tronWeb.defaultAddress.hex,
            ...options
        };

        if(!options.privateKey && !options.address)
            return callback('Function requires either a private key or address to be set');
```
the check is useless because the way `options` is built makes the condition impossible, right?

**Comment by Kondax** [comment]
I made the change as the "official" launch isn't until the 8th, however I
can add backwards support for the string.

The condition is still possible as no default private key or address could
be set.

**Comment by sullof** [comment]
It makes sense.

**Comment by sullof** [comment]
Anyway, I would throw an error in `typeof options !== 'object'`.

**Pull request merged**
